package com.kevinweb.app.config.props;

import com.kevinserver.props.PropKnife;
import com.kevinserver.props.annotations.PropBind;
import com.kevinserver.props.annotations.DefaultValue;

/**
 * This code is generated by Freemaker from config
 * @author xukai
 */
public class InitProp {
	private static final String PROP_FILE = "init.properties";
	
	@PropBind("isDebug")
	@DefaultValue("true")
	public static boolean DEBUG;
	/**
	 * JFinal是否为开发模式
	 */
	@PropBind("config.devMode")
	@DefaultValue("true")
	public static boolean CFG_DEV_MODE;
	/**
	 * 连接数据库类型
	 */
	@PropBind("db.type")
	@DefaultValue("mysql")
	public static String DB_TYPE;
	@PropBind("db.mysql.driverClass")
	@DefaultValue("com.mysql.jdbc.Driver")
	public static String DB_DRIVER_CLASS;
	@PropBind("db.mysql.jdbcUrl")
	@DefaultValue("jdbc:mysql://127.0.0.1:3306/jfinaluibv2?characterEncoding=UTF-8&autoReconnect=true&failOverReadOnly=false&zeroDateTimeBehavior=convertToNull")
	public static String DB_JDBC_URL;
	@PropBind("db.mysql.username")
	@DefaultValue("root")
	public static String DB_USERNAME;
	@PropBind("db.mysql.password")
	@DefaultValue("123123")
	public static String DB_PASSWORD;
	
	public static void load() throws IllegalArgumentException, IllegalAccessException {
		long st = System.currentTimeMillis();
		PropKnife.bind(InitProp.class, PROP_FILE);
		System.out.println(System.currentTimeMillis() - st);
	}
	
	public static void reload() throws IllegalArgumentException, IllegalAccessException {
		load();
	}
}
